version: 2

sources:
  - name: snowflake_account_usage
    database: snowflake
    schema: account_usage

    quoting:
      database: false
      schema: false
      identifier: false
    
    tables:
      - name: query_history
